### ISSUE TITLE
[pocket] add support for tags/labels

### ISSUE THREAD

**Issue by e-krebs** [e-krebs/pile#45]
- [x] show tags #46 
- [x] allow to add tags #50
- [x] allow to remove tags #50 
- [x] allow to filter by tags #51
- [ ] update images on the repo & on the chrome web store
